# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0 # Use a specific version
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 23.12.1 # Use the latest stable version
    hooks:
      - id: black
        language_version: python3 # Set the Python version for black

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0 # Use the latest stable version of flake8
    hooks:
      - id: flake8
