cnn:
  adaptive_pool:
  - 128
  - 128
  fc1:
  - 2097152
  - 512
  fc2:
  - 512
  - 128
  input_channels: 3
dataset:
  batch_size: 64
  dataloader_shuffle: true
  imgs_per_style: 1000
  input_shape:
  - 3
  - 512
  - 512
  processed_path: data/processed
  raw_path:
  seed: 2476
  styles:
  - Academic_Art
  - Art_Nouveau
  - Baroque
  - Expressionism
  - Japanese_Art
  - Neoclassicism
  - Primitivism
  - Realism
  - Renaissance
  - Rococo
  - Romanticism
  - Symbolism
  - Western_Medieval
  test_size: 0.2
hyperparameters:
  epochs: 2
  lr: 1e-4
model: resnet18
profile: true
weights: outputs/2024-01-17/17-13-02
