cnn:
  adaptive_pool:
  - 128
  - 128
  fc1:
  - 2097152
  - 512
  fc2:
  - 512
  - 128
  input_channels: 3
dataset:
  batch_size: 64
  dataloader_shuffle: true
  imgs_per_style: 100
  input_shape:
  - 3
  - 512
  - 512
  processed_path: outputs\2024-01-15\13-00-51
  raw_path: data/raw
  seed: 2476
  test_size: 0.2
  batch_size: 64
  dataloader_shuffle: True
  input_shape: [1,512,512]
# Path where train_model.py or train_test_viz.pt saves the weights
# Make sure weights match the model
# weights is only used in predict_model.py
weights: C:\Users\Hasan\OneDrive\Desktop\Projects\ML-Ops\outputs\2024-01-10\21-06-05
