# Choose model from: CNN, resnet18,resnet34,resnet50,tf_efficientnet_lite0

model: "CNN"
cnn:
    # Make sure input_channels match with input_shape in dataset
    input_channels: 1
    adaptive_pool: [128,128]
    fc1: [2097152,512] # (128 * 128 * 128, 12)
    fc2: [512, 128]
hyperparameters:
  lr: 1e-4
  epochs: 6
dataset:
  # Path where raw data is stored, includes Academic_Art, Art_nouveau, etc...
  # Keep Raw as relative Path
  # In Docker /data/raw - /data/raw
  # Windows Full Path
  raw_path: C:\Users\Hasan\OneDrive\Desktop\Projects\ML-Ops\data\raw
  # Path where make_dataset.py saves .pt files
  processed_path: C:\Users\Hasan\OneDrive\Desktop\Projects\ML-Ops\data\processed
  styles:  ["Symbolism", "Japanese_Art"]
  imgs_per_style: 100
  seed: 2476
  test_size: 0.2
  batch_size: 64
  dataloader_shuffle: True
  input_shape: [1,512,512]
# Path where train_model.py or train_test_viz.pt saves the weights
# Make sure weights match the model
# weights is only used in predict_model.py
weights: C:\Users\Hasan\OneDrive\Desktop\Projects\ML-Ops\outputs\2024-01-10\21-06-05
