cnn:
  adaptive_pool:
  - 128
  - 128
  fc1:
  - 2097152
  - 512
  fc2:
  - 512
  - 128
  input_channels: 3
dataset:
  batch_size: 64
  dataloader_shuffle: true
  imgs_per_style: 100
  input_shape:
  - 3
  - 512
  - 512
  processed_path: outputs\2024-01-15\13-00-51
  raw_path: data/raw
  seed: 2476
  styles:
  - Symbolism
  - Romanticism
  test_size: 0.2
hyperparameters:
  epochs: 2
  lr: 1e-4
model: resnet18
profile: true
weights: outputs\2024-01-15\13-18-52
