name: Deployment Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install Format & Linter Dependencies
        run: |
          pip install flake8 black "black[jupyter]"

      - name: Check code with Black
        run: |
          black --check .

      - name: Lint with flake8
        run: |
          flake8 .
      - name: Run Units
        run: |
          make requirements
          pip install pytest
          pytest tests/
        env:
          LOCAL_PATH: ${{ github.workspace }}
