name: DVC Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: DVC Pull
        run: |
          pip install dvc dvc[gdrive]
          dvc pull
        env:
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}

      - name: Cache DVC
        uses: actions/cache@v2
        with:
          path: |
            .dvc/cache
          key: ${{ runner.os }}-dvc-${{ hashFiles('.dvc.dvc') }}
          restore-keys: |
            ${{ runner.os }}-dvc-

      - name: Run Tests
        run: |
          # Your test commands go here
